import { Platform, StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#FAFAF9',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginTop: 30,
    marginBottom: 20,
    gap: 10,
  },
  backButton: {
    width: 48,
    height: 48,
    borderRadius: 15,
    backgroundColor: '#4CAF50',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontFamily: 'DMSans_500Medium',
    fontSize: 18,
    lineHeight: 23,
    color: '#000000',
  },
  tabsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 8,
    marginHorizontal: 20,
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#EBEBEB',
    borderRadius: 14,
    marginBottom: 20,
  },
  tab: {
    flex: 1,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
  },
  tabActive: {
    backgroundColor: '#4CAF50',
  },
  tabText: {
    fontFamily: 'DMSans_500Medium',
    fontSize: 16,
    color: '#000000',
  },
  tabTextActive: {
    color: '#FFFFFF',
  },
  listContainer: {
    paddingHorizontal: 20,
    paddingBottom: 100,
    gap: 10,
  },
  orderCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#EBEBEB',
    borderRadius: 14,
    padding: 16,
    marginBottom: 18,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  orderedByCol: {
    flexDirection: 'column',
    gap: 4,
  },
  orderedByLabel: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 14,
    color: '#898989',
    lineHeight: 18,
  },
  listCustomerName: {
    fontFamily: 'DMSans_500Medium',
    fontSize: 16,
    color: '#000000',
    lineHeight: 21,
  },
  statusText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 14,
    lineHeight: 18,
  },
  cardBody: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 15,
  },
  avatar: {
    width: 100,
    height: 100,
    borderRadius: 20,
  },
  productDetails: {
    flex: 1,
    flexDirection: 'column',
    gap: 8,
  },
  productNameWeight: {
    flexDirection: 'column',
    gap: 1,
  },
  productName: {
    fontFamily: 'DMSans_500Medium',
    fontSize: 14,
    color: '#000000',
    lineHeight: 20,
  },
  productWeight: {
    fontFamily: 'DMSans_500Medium',
    fontSize: 14,
    color: '#000000',
    lineHeight: 20,
  },
  locationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  locationText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 14,
    color: '#898989',
    lineHeight: 20,
  },
  locationIconBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  distanceText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 14,
    color: '#898989',
    lineHeight: 18,
  },
  priceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 4,
  },
  priceText: {
    fontFamily: 'DMSans_700Bold',
    fontSize: 18,
    color: '#4CAF50',
    lineHeight: 23,
  },
  orderIdRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 18,
  },
  orderIdLabel: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 14,
    color: '#898989',
    lineHeight: 18,
  },
  orderIdValue: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 14,
    color: '#000000',
    lineHeight: 18,
  },
  bottomBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 84,
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingBottom: 20,
    ...Platform.select({
      ios: {
        shadowColor: 'rgba(76, 175, 80, 0.15)',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 1,
        shadowRadius: 4,
      },
      android: {
        elevation: 8,
      },
      web: {
        boxShadow: '0px 0px 4px rgba(76, 175, 80, 0.15)',
      },
    }),
  },
  tabItem: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 60,
    gap: 3,
  },
  tabIconBox: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabIcon: {
    width: '100%',
    height: '100%',
  },
  tabLabel: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 14,
    lineHeight: 18,
    color: '#737373',
  },
  tabLabelActive: {
    color: '#4CAF50',
  },
  detailsContainer: {
    padding: 20,
    gap: 20,
    paddingBottom: 40,
  },
  bannerCompleted: {
    backgroundColor: '#4CAF50',
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bannerCancelled: {
    backgroundColor: '#E62326',
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bannerText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 16,
    color: '#FFFFFF',
  },
  customerCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    padding: 10,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
    borderWidth: 1.5,
    borderColor: '#EBEBEB',
    gap: 15,
  },
  customerInfo: {
    flex: 1,
    gap: 4,
  },
  customerName: {
    fontFamily: 'DMSans_500Medium',
    fontSize: 18,
    color: '#000000',
  },
  customerLocation: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 14,
    color: '#8C8C8C',
  },
  actionButtons: {
    flexDirection: 'row',
    gap: 10,
  },
  btnReject: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#4CAF50',
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
  },
  btnRejectText: {
    color: '#000000',
    fontFamily: 'DMSans_500Medium',
    fontSize: 16,
  },
  btnAccept: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: '#4CAF50',
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
  },
  btnAcceptText: {
    color: '#FFFFFF',
    fontFamily: 'DMSans_500Medium',
    fontSize: 16,
  },
  summaryContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    padding: 14,
    borderWidth: 1.5,
    borderColor: '#EBEBEB',
    gap: 10,
  },
  summaryBox: {
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    paddingHorizontal: 18,
    paddingVertical: 15,
    borderWidth: 1.5,
    borderColor: '#EBEBEB',
  },
  summaryTitle: {
    fontFamily: 'DMSans_500Medium',
    fontSize: 16,
    marginBottom: 12,
    color: '#000000',
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  summaryLabel: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 14,
    color: '#6D6D6D',
  },
  summaryValue: {
    fontFamily: 'DMSans_500Medium',
    fontSize: 14,
    color: '#000000',
  },
  totalBox: {
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    paddingHorizontal: 18,
    paddingVertical: 15,
    borderWidth: 1.5,
    borderColor: '#EBEBEB',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  totalLabel: {
    fontFamily: 'DMSans_500Medium',
    fontSize: 16,
    color: '#000000',
  },
  totalValue: {
    fontFamily: 'DMSans_700Bold',
    fontSize: 20,
    color: '#000000',
  },
  totalBoxCompleted: {
    backgroundColor: '#4CAF50',
    borderRadius: 14,
    paddingVertical: 16,
    paddingHorizontal: 20,
    marginTop: 10,
    gap: 8,
  },
  totalRowCompleted: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  totalLabelCompleted: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 16,
    color: '#FFFFFF',
  },
  totalValueCompleted: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 16,
    color: '#FFFFFF',
  },
  completedOnText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 16,
    color: '#FFFFFF',
  },
  trackBtn: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#4CAF50',
    borderRadius: 14,
    paddingVertical: 16,
    marginTop: 20,
  },
  trackBtnText: {
    color: '#FFFFFF',
    fontFamily: 'DMSans_500Medium',
    fontSize: 16,
  },
  fixedBottomBar: {
    padding: 20,
    backgroundColor: '#FAFAF9',
    paddingBottom: 40,
  },
  orderMeta: {
    alignItems: 'flex-end',
    justifyContent: 'center',
    minWidth: 80,
  },
  orderTime: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 12,
    lineHeight: 16,
    color: '#8C8C8C',
  },
});
